### PR TITLE
explicit solitidy version in config due to out of gas errors

### PR DESCRIPTION
**Pull request by chaseadam**

### CODE REVIEW

**Comment by peterbroadhurst** [comment]
@joshmobley @chaseadam - I suspect this relates to the change in the _default_ target for compilation changing in solc from `byzantium` to `constantinople` (well actually `petersburg`).
That happened at `0.5.5` - so I think `0.5.4` is safe with the default options.
But I also wonder if it would be better to pick up the latest `0.5` compiler still, and instead set the target explicitly.

**Comment by chaseadam** [comment]
#3

**Comment by joshmobley** [comment]
Makes sense to me -- is there a specific testing battery we should conduct? Also -- whatever we do here we'll need to open against https://github.com/kaleido-io/drizzle-kaleido-box as well

**Comment by chaseadam** [comment]
might make sense to add a test to run through a migration (would have caught this)

**Review by joshmobley — APPROVED** [review]
🚢 🚀

**Comment by peterbroadhurst** [comment]
Merging now to ensure a known working configuration. Then we can work on future changes to pick up new compiler options.

**Pull request merged**
